version: '3'
services:
  backend:
    container_name: actix-backend
    env_file:
      - ./configuration/local/.env
    build:
      dockerfile: ./configuration/local/Dockerfile
    tty: true
    ports:
      - "8000:8000"
    restart: unless-stopped
    working_dir: /app
    environment:
      CONTAINER_ENV: local
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - project-net

  postgres:
    platform: linux/amd64
    image: postgres:15.2-alpine
    container_name: postgres-actix
    env_file:
      - configuration/local/.env
    ports:
      - '5432:5432'
    volumes:
      - project-pgsql-data:/var/lib/postgresql/data
    networks:
      - project-net

volumes:
  project-pgsql-data:

networks:
  project-net:
    driver: bridge